### ISSUE TITLE
Can I use this engine for for developing paid apps?

### ISSUE THREAD

**Issue by mchinnakonda** [PBS-KIDS/HTML5-Storybook#3]
Hi,

I am very interested to use your story book engine for developing custom mobile story book apps and monetize them and wanted to check with you to see if there might be any issues in using your engine files to develop my apps and publish them in various app stores (ios, android, windows etc.). Just to clarify, I will only be using your engine files and will use my own set of images, sounds, texts etc. for developing the apps.

Could you let me know if I can use your files for free or if I need to pay a one time licensing or royalty fees?

Your inputs will help me proceed accordingly.

Thanks,
Manoj

**Comment by mcscooter** [comment]
Hi Manoj,

Yes, as long as you adhere to the stipulations in the license at: https://github.com/PBS-KIDS/HTML5-Storybook/blob/master/licenses.txt

There is no charge for using it on revenue generating applications. If you make any changes or additions to the engine that others might find useful we'd love for you to share them back to the project if possible.

Regards,

Scott

**Comment by mchinnakonda** [comment]
Thanks for your clarification Scott. 

Just FYI, I posted this question to PBS KIds through their website before seeing your reply. Wanted to let you know in case the question will be routed to you one more time :)

Thanks,
Manoj
